In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_list1

[1, 2, 3, 4]

In [4]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [7]:
my_lists = [my_list1, my_list2]

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np_array(my_lists)

NameError: name 'np_array' is not defined

In [10]:
my_array2 = np.array(my_lists)

In [11]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.dtype

dtype('int64')

In [13]:
my_array2.shape

(2, 4)

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
my_zeros = np.zeros(5)

In [16]:
my_zeros.dtype

dtype('float64')

In [17]:
np.ons((5,5))

AttributeError: module 'numpy' has no attribute 'ons'

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.empty((3,4))

array([[ 4.94065646e-323,  0.00000000e+000, -1.49166815e-154,
         2.32035119e+077],
       [ 2.18885861e-314,  2.18887890e-314,  2.17877348e-314,
         2.17764301e-314],
       [ 2.18029807e-314,  2.18220544e-314,  2.18887893e-314,
         2.18886818e-314]])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [22]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])