In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
np.random.randn(10)

array([ 0.12169477,  0.14819204,  0.04589385, -1.43623093,  0.58650922,
       -0.0616409 ,  0.83203104,  0.0304747 , -0.01487613, -0.30824306])

In [7]:
A = np.random.randn(10)

In [8]:
B = np.random.randn(10)

In [9]:
A + B

array([-1.66579861,  2.50707652, -0.22668015,  0.22519748,  1.98849063,
       -0.04968193,  0.64496298, -0.72696205, -0.26174435, -0.88872182])

In [10]:
np.add(A, B)

array([-1.66579861,  2.50707652, -0.22668015,  0.22519748,  1.98849063,
       -0.04968193,  0.64496298, -0.72696205, -0.26174435, -0.88872182])

In [11]:
A * B

array([ 0.25362729,  1.50185458, -0.25103106, -1.69694031,  0.23715206,
       -0.1023061 ,  0.09255846, -0.00674327, -0.08241937,  0.18961663])

In [12]:
np.muliply(A, B)

AttributeError: module 'numpy' has no attribute 'muliply'

In [13]:
np.multiply(A, B)

array([ 0.25362729,  1.50185458, -0.25103106, -1.69694031,  0.23715206,
       -0.1023061 ,  0.09255846, -0.00674327, -0.08241937,  0.18961663])

In [14]:
np.maximum(A, B)

array([-0.16950352,  1.5171736 ,  0.40034955,  1.42012266,  1.8610623 ,
        0.29597545,  0.42942004,  0.00916053,  0.18463837, -0.35581722])