In [1]:
5/2

2.5

In [2]:
import numpy as np

In [3]:
arr1 = np.array(((1,2,3,4)))

In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])

In [6]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [8]:
arr1 + arr1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [9]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
arr1 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [11]:
arr1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

In [12]:
arr2 = np.arange(1, 11)

In [13]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr2 1

SyntaxError: invalid syntax (<ipython-input-14-1d4b7d2a531b>, line 1)

In [15]:
arr2[1]

2

In [16]:
arr2[1:5]

array([2, 3, 4, 5])

In [17]:
arr2[1:5] = 20

In [18]:
arr2

array([ 1, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [19]:
arr2 = np.arange(0, 11)

In [20]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_arr = arr2[0:6]

In [22]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [23]:
slice_arr[:] = 99

In [24]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy = arr2.copy

In [27]:
arr_copy

<function ndarray.copy>

In [28]:
arr_copy = arr2.copty()

AttributeError: 'numpy.ndarray' object has no attribute 'copty'

In [29]:
arr_copy = arr2.copy()

In [30]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.arange([[1,2,3], [4,5,6], [7,8,9]])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [32]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [33]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr_2d[0]

array([1, 2, 3])

In [35]:
arr_2d[0][1]

2

In [36]:
arr_2d[0, 1]

2

In [37]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr_2d[:2, :1]

array([[1],
       [4]])

In [39]:
arr_2d[2:, 1:]

array([[8, 9]])

In [40]:
arr_2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [41]:
arr_10 = np.arange(10, 10)

In [42]:
arr_10

array([], dtype=int64)

In [43]:
arr_10 = np.arange([10, 10])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [44]:
arr_10 = np.zeros(10, 10)

TypeError: data type not understood

In [45]:
arr_10 = np.zeros([10, 10])

In [46]:
arr_10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
length = arr_10.shapre[1]

AttributeError: 'numpy.ndarray' object has no attribute 'shapre'

In [48]:
length = arr_10.shape[1]

In [49]:
length

10

In [50]:
length = arr_10.shape[0]

In [51]:
length

10

In [52]:
for i in range(length):
    arr_10[i] = i

In [53]:
arr_10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [54]:
arr_10[2]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [55]:
arr_10[2,4]

2.0

In [56]:
arr_10[[2, 4]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])