In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('my_array', arr)

In [6]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.arange(10)

In [8]:
np.savez('zip_array.npz', x = arr, y = arr1)

In [10]:
zip = np.load('zip_array.npz')

In [11]:
zip['x']

array([0, 1, 2, 3, 4])

In [12]:
zip['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])